### PR TITLE
WinRM V2

### LINKED ISSUE #106: Handle serialized CLIXML OutputFormat
One of the PowerShell options is:
> -OutputFormat {Text | XML}
> Determines how output from Windows PowerShell is formatted. Valid values are "Text" (text strings) or "XML" (serialized CLIXML format).

This gem doesn't parse the latter, so it seems like it would be good to always capture output as text. Unfortunately, this option only seems to control the stdout stream. The stderr stream is always written as CLIXML, as seen in this pry session. Changing the option from Text to XML effects stdout but not stderr:

```
[1] pry(#<WinRM::WinRMWebService>)> run_cmd("powershell -outputFormat Text -encodedCommand #{script}", &block)
=> {:data=>
  [{:stdout=>"Hello"},
   {:stdout=>"\n"},
   {:stderr=>"#< CLIXML\r\n"},
   {:stderr=>"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">, world!_x000D__x000A_</S></Objs>"}],
 :exitcode=>0}
[2] pry(#<WinRM::WinRMWebService>)> run_cmd("powershell -outputFormat XML -encodedCommand #{script}", &block)
=> {:data=>
  [{:stdout=>"#< CLIXML\r\n"},
   {:stderr=>"#< CLIXML\r\n"},
   {:stdout=>"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Output\">Hello</S><S S=\"Output\">_x000A_</S></Objs>"},
   {:stderr=>"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">, world!_x000D__x000A_</S></Objs>"}],
 :exitcode=>0}
```

Actually, even though it is always XML it does look like using Text at least limits the stderr to XML only containing serialized strings, as opposed to more complex types when using XML:

```
[3] pry(#<WinRM::WinRMWebService>)> run_cmd("powershell -outputFormat Text -encodedCommand #{script}", &block)
=> {:data=>
  [{:stdout=>"Hello"},
   {:stdout=>"\n"},
   {:stderr=>"#< CLIXML\r\n"},
   {:stderr=>
     "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">      Write-Host 'Hello'_x000D__x000A_</S><S S=\"Error\">      Write-Error 'foo'_x000D__x000A_</S><S S=\"Error\">      $host.ui.WriteErrorLine(', world!')_x000D__x000A"},
   {:stderr=>
     "_</S><S S=\"Error\"> : foo_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep _x000D__x000A_</S><S S=\"Error\">   tion_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio _x000D__x000A_</S><S S=\"Error\">   n_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S><S S=\"Error\">, world!_x000D__x000A_</S></Objs>"}],
 :exitcode=>0}
[4] pry(#<WinRM::WinRMWebService>)> run_cmd("powershell -outputFormat XML -encodedCommand #{script}", &block)
=> {:data=>
  [{:stdout=>"#< CLIXML\r\n"},
   {:stderr=>"#< CLIXML\r\n"},
   {:stdout=>"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Output\">Hello</S><S S=\"Output\">_x000A_</S></Objs>"},
   {:stderr=>
     "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"Error\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.ErrorRecord</T><T>System.Object</T></TN><ToString>foo</ToString><MS><B N=\"writeErrorStream\">true</B><Obj "},
   {:stderr=>
     "N=\"Exception\" RefId=\"1\"><TN RefId=\"1\"><T>Microsoft.PowerShell.Commands.WriteErrorException</T><T>System.SystemException</T><T>System.Exception</T><T>System.Object</T></TN><ToString>Microsoft.PowerShell.Commands.WriteErrorException: foo</ToString><Props><S N=\"Message\">foo</S><Obj N=\"Data\" RefId=\"2\"><TN RefId=\"2\"><T>System.Collections.ListDictionaryInternal</T><T>System.Object</T></TN><DCT /></Obj><Nil N=\"InnerException\" /><Nil N=\"TargetSite\" /><Nil N=\"StackTrace\" /><Nil N=\"HelpLink\" /><Nil N=\"Source\" /><I32 N=\"HResult\">-2146233087</I32></Props></Obj><Nil N=\"TargetObject\" /><S N=\"FullyQualifiedErrorId\">Microsoft.PowerShell.Commands.WriteErrorException</S><Obj N=\"InvocationInfo\" RefId=\"3\"><TN RefId=\"3\"><T>System.Management.Automation.InvocationInfo</T><T>System.Object</T></TN><ToString>System.Management.Automation.InvocationInfo</ToString><Props><Obj N=\"MyCommand\" RefId=\"4\"><TN RefId=\"4\"><T>System.Management.Automation.ScriptInfo</T><T>System.Management.Automation.CommandInfo</T><T>System.Object</T></TN><ToString>      Write-Host 'Hello'_x000A_      Write-Error 'foo'_x000A_      $host.ui.WriteErrorLine(', world!')_x000A_</ToString><Props><SBK N=\"ScriptBlock\">      Write-Host 'Hello'_x000A_      Write-Error 'foo'_x000A_      $host.ui.WriteErrorLine(', world!')_x000A_</SBK><S N=\"Definition\">      Write-Host 'Hello'_x000A_      Write-Error 'foo'_x000A_      $host.ui.WriteErrorLine(', world!')_x000A_</S><Obj N=\"OutputType\" RefId=\"5\"><TN RefId=\"5\"><T>System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Management.Automation.PSTypeName, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]</T><T>System.Object</T></TN><LST /></Obj><S N=\"Name\"></S><S N=\"CommandType\">Script</S><S N=\"Visibility\">Public</S><S N=\"ModuleName\"></S><Nil N=\"Module\" /><S N=\"RemotingCapability\">PowerShell</S><Obj N=\"ParameterSets\" RefId=\"6\"><TN RefId=\"6\"><T>System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Management.Automation.CommandParameterSetInfo, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]</T><T>System.Object</T></TN><LST><S></S></LST></Obj></Props><MS><S N=\"Namespace\"></S><S N=\"HelpUri\"></S></MS></Obj><Obj N=\"BoundParameters\" RefId=\"7\"><TN RefId=\"7\"><T>System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</T><T>System.Object</T></TN><DCT /></Obj><Obj N=\"UnboundArguments\" RefId=\"8\"><TN RefId=\"8\"><T>System.Collections.Generic.List`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</T><T>System.Object</T></TN><LST /></Obj><I32 N=\"ScriptLineNumber\">0</I32><I32 N=\"OffsetInLine\">0</I32><I64 N=\"HistoryId\">1</I64><S N=\"ScriptName\"></S><S N=\"Line\"></S><S N=\"PositionMessage\"></S><S N=\"PSScriptRoot\"></S><Nil N=\"PSCommandPath\" /><S N=\"InvocationName\"></S><I32 N=\"PipelineLength\">0</I32><I32 N=\"PipelinePosition\">0</I32><B N=\"ExpectingInput\">false</B><Obj N=\"CommandOrigin\" RefId=\"9\"><TN RefId=\"9\"><T>System.Management.Automation.CommandOrigin</T><T>System.Enum</T><T>System.ValueType</T><T>System.Object</T></TN><ToString>Internal</ToString><I32>1</I32></Obj><Nil N=\"DisplayScriptPosition\" /></Props></Obj><I32 N=\"ErrorCategory_Category\">0</I32><S N=\"ErrorCategory_Activity\">Write-Error</S><S N=\"ErrorCategory_Reason\">WriteErrorException</S><S N=\"ErrorCategory_TargetName\"></S><S N=\"ErrorCategory_TargetType\"></S><S N=\"ErrorCategory_Message\">NotSpecified: (:) [Write-Error], WriteErrorException</S><B N=\"SerializeExtendedInfo\">false</B><Nil N=\"PSMessageDetails\" /></MS></Obj><S S=\"Error\">, world!_x000D__x000A_</S></Objs>"}],
 :exitcode=>0}
```

### PR DESCRIPTION
**Pull request by sneal**
closes #106, #105, #169, #197, #203, #208, #194

### CODE REVIEW

**Comment by mwrock** [comment]
Got Powershell running here with equivelent functionality as the spike. Just need to properly parse the powershell output from the binary blob.

`Connection.shell` now takes a block and will close the shell when the block completes if given. While the finalizer should take care of this, this allows for earlier freeing of the connection if necessary.

Also added a `run_wql` right off of connection since wql is not run in a shell.

**Comment by mwrock** [comment]
Found some time to get back to this last night. The `MessageFactory` now has a `parse_bytes` method that can create a psrp message from raw bytes. I added accessors for each part described in the spec. Currently we munge fragments into the outer message shell but we can decompose that when we need to.

There is an additional `decoder` now specifically for powershell however we may soon need to break up the output processor as well. This will all definitely need some refactoring after the rest of the output handling is added.

Currently it can handle basic powershell output. It cant yet handle error responses nor does it deal well with commands containing quotes and line endings. So thats gonna be next.

**Comment by mwrock** [comment]
Just rebased on top of current master. Both unit and integration tests are green "on my machine" but looks like something is not appveyor friendly.

Beyond fixing appveyor there is some rather heinous stuff going on in output processing with the message_types and code duplication. Will clean that up.

**Comment by sneal** [comment]
@mwrock Exciting! I plan to get back to this sometime later this week.

**Comment by svmastersamurai** [comment]
:+1: y'all are doing god's work

**Comment by mwrock** [comment]
I believe these last commits complete the the functional parity between v2/v1 in all regards other then the PSRP implementation. At this point there are two key TODOs to consider the PSRP implementation ready:
1. Propper quote and xml escaping of the command prior to embedding it in the `clixml`
2. Implementing multi fragment messages

**Comment by mwrock** [comment]
oh and figuring out why the psrp does not work with nano

**Comment by mwrock** [comment]
Got nano working and in the process I think figured out the mystery of needing to send the keepalive message for the powershell runspace. There is a temporary hack added for now but I'm going to add the ability to poll the runspace state and not rerurn a shell until it is in the `openned` state.

**Comment by mwrock** [comment]
I think message fragmenting is the only major missing piece here now. Gonna start investigating that more deeply. The main thing to figure out is just when to fragment. After my initial readings of the spec, it was unclear where the limits of a single fragment length is specified.

**Comment by mwrock** [comment]
Started  refactoring for fragmentation. This last commit breaks up the `Message` class and introduces a separate `Fragment` class along with a `MessageFragmenter` and `MessageDefragmenter` class that will do the dissassembly/reassembly of fragments to and from messages.

This is largely a "dumb" implementation right now that assumes a single fragment but provides a structure where the final implementation can be "filled in". The following now needs to happen:
* Do some tidying up especially in the unit tests
* Implement the `MessageDefragmenter` to support multi fragment responses
* Implement the `MessageFragmenter` to support multi fragment commands with a contrived fragment length (more on this in a bit).
* Issue a `WSMV` `Configuration` message to get the `MaxEnvelopeSizeKB` setting on the endpoint in order to calculate the actual fragment length.

One thing I discovered researching this and reverse engineering fragments from powershell remoting commands is that the PSRP "lies" about the maximum `blob_length` of a fragment. It states a max of 32k but there is in fact no limit. Well the limit is inherited from the `MaxEnvelopeSizeKB` on the endpoint which governs the limit of the entire SOAP message. If the SOAP message exceeds this limit, the endpoint will respond with a HTTP 413 (too large). Further the Winrm `MaxEnvelopeSize` header has absolutely no impact from what I can tell. The only authoritative limit lives on the endpoint.

Now one can issue commands to on the endpoint to get this setting on later windows versions but not on 2008 R2 and earlier. However, there is a `configuration` WSMV message type one can use to "legally" get these settings and we can use this to calculate what the maximum blob size of our fragments should be. Different versions of windows have different default sizes. 2012R2 and 2016/Nano have a 512K limit while 2008R2 is around 128K.

**Comment by sneal** [comment]
Good to know, almost need a backlog of stories for this work. Keep it up :+1:, I probably won't have much time over the next few weeks to work on this.

**Comment by mwrock** [comment]
Yay! Fragmentation/Defragmentation is working. Remaining items are now:
* Base max blob length from MaxEnvelopeSize in fragmenting
* Rewrite readme
* Figure out why this is not working on 2008R2

Then I'll start working on getting winrm-fs and test-kitchen to use this which should provide good thorough real world testing.

**Comment by mwrock** [comment]
ok integration tests are working on 2008R2 and nano. I think I'm gonna release a dev gem and blog about this over the weekend. Next step is integrating with winrm-fs (perhaps a 1.0). Cant wait to get benchmarks on file copy perf comparisons!

**Comment by mwrock** [comment]
winrm-fs is mostly where it needs to be now and I've got a [WIP pr](https://github.com/test-kitchen/test-kitchen/pull/1061) in Test-kitchen basically working. The first thing that pr has uncovered is that the error output here is way too verbose. So thats the next thing.

**Comment by mwrock** [comment]
refactoring `power_shell.rb` and `CommandOutputProcessor`. Currently both shells expose a `run` method for executing a command and returning `WinRM::Output`. At least for debugging and exploration purposes now and possibly for the ability to extend PSRP in the future, I have wanted methods on the PSRP shell that return a stream of raw PSRP messages instead of decoded output. Also want a way to simply send a message not necessarily associated with a shell that returns a message stream (for example messages that query runspaces).

These last several commits add these messages and add some required refactoring to the `OutputProcessor` now renamed `ReceiveResponseReader`. Integration tests all pass but unit tests are currently broken.

This is also a precursor to some refactoring of PSRP message decoding. Its become apparent that we need "strong" types for some PSRP complex message types. Things like Error_Record, Pipiline_Host_call and others should have their complex data better encapsulated. Without this we risk some XSLT messiness as we improve the error output. I dont intend for this to become a full CLIXML deserializer but its a step in that direction.

**Comment by mwrock** [comment]
Current TODOs:
- [ ] Fix unit tests
- [ ] Add unit tests to cover new public methods
- [ ] Add a few integration tests for the new powershell methods
- [ ] Create `MessageType` classes for needed PSRP complex objects
- [ ] Clean up Error Record output to match (at least closely) what native PS remoting renders

**Comment by mwrock** [comment]
We now have more formal `MessageData` classes that more cleanly encapsulate the PSRP message data which also cleans up the powershell output decoding. Also we now take an "opt in" approach to decuding messages instead of choosing a list of message types to ignore.

The `ErrorRecord` message data is currently just a skeleton and the decoder uses the old logic in the output transformation. So the next step is to properly structure the error record and then closely emulate native powershell in rendering it.

**Comment by mwrock** [comment]
error record data looks good now but lets watch this one closely because I feel I'm missing key error scenarios.

Gonna start retrofitting winrm-elevated now

**Comment by mwrock** [comment]
Refactored `ShellFactory` to load shells dynamically. This allows outside gem to create derrived `Shell` classes. There are likely not many use cases here but the winrm-elevated is a exemplary case. This refactoring is targetted to making what was once a runner into a shell. So one can call:
```
conn.shell(:elevated) do |shell|
  shell.username = 'System'
  shell.password = nil
  shell.run('$PSVersionTable') do |stdout, stderr|
    STDOUT.print stdout
    STDERR.print stderr
  end
end
```

This way consuming applications dont have to have any special code path for elevated commands. Its just a shell.

**Comment by sneal** [comment]
@mwrock Uh oh, this just got real!

**Comment by svmastersamurai** [comment]
just in time for chefconf ;)

**Comment by mwrock** [comment]
@sneal I think I truly am done here now after some final cleanup. I've confirmed integration tests work against 2k8r2, 2012R2 (with and without WMF5) and Nano. It also works with pending v1,0s of winrm-fs and winrm-elevated as well as a Test-Kitchen PR pulling in all of those. I'm thinking we let it bake in Test-Kitchen for a couple months before submitting to vagrant.

I realize its a huge PR and alot changed since you touched it so I understand if you need lots of time to digest. Also feel free to ping me if you want to walk through any of this.

**Comment by mwrock** [comment]
To test against a Test-Kitchen environment leveraging all winrm-v2 PRs, `bundle install` from the winrm-v2 branch of https://github.com/chocolatey/chocolatey-cookbook/tree/winrm-v2 and then run `bundle exec kitchen verify`

**Comment by mwrock** [comment]
Here is another good test repo: https://github.com/mwrock/DSCTextfile

This uses the kitchen-DSC driver and thus does not use chef at all. It runs direct remote DSC commands to converge the machine.

**Comment by chris-rock** [comment]
Guys, you do awesome work!

**Comment by sneal** [comment]
Finally looking at this again for the first time in a few months...

**Comment by sneal** [comment]
Since we're breaking backwards compatibility, I'd like to have the [Output class not be a Hash](https://github.com/WinRb/WinRM/pull/103).

**Comment by mwrock** [comment]
Sounds good @sneal. I'm thinking of essentially just exposing an exitcode method and, at least for now, keeping a internal hash to track the data so much of the inner `Output` code will remain the same you just won't be able to access it as a hash. That sound good?

**Comment by mwrock** [comment]
@sneal Here is what I have the output looking like: https://gist.github.com/mwrock/470d06301dff66c2b20b41d67c39a62a

**Comment by mwrock** [comment]
I'll be adding yard docs, etc, etc

**Comment by mwrock** [comment]
Updated `Output` and added commits to all downstream PRs

**Comment by sneal** [comment]
@mwrock It just got real!

**Comment by mwrock** [comment]
oh yeah!

**Pull request merged**
