### PR TITLE
Allow shell options to be passed when creating shell

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by sneal** [comment]
Its _slightly_ odd to have cmd shell options at the session level. It seems more appropriate when a cmd shell is opened.

```
conn = WinRM::Connection.new(conn_opts)
conn.shell(:cmd, :code_page: '437') do |shell|
  output = shell.run('dir')
end
```

Although convenience may outweigh that since something like code_page isn't likely to change between shells for a connection but working_dir could. Hmm...

**Comment by mwrock** [comment]
Yeah thats a good point, `env vars` are in the same boat.

**Comment by mwrock** [comment]
One thought is to add a shell_opts hash to the shell factory and the base shell that defaults to an empty hash.  The elevated shell can benefit from that too when alternate creds are desired for the task. Currently that can only be set from a property accessor. This would be purely additive and non breaking (2.1.0).

**Comment by mwrock** [comment]
@sneal I updated the pr to be closer to the original api and allow shell_opts to be passed through when creating the shell.

**Comment by sneal** [comment]
LGTM. We should probably add a test to ensure the shell options work end-to-end.

**Comment by mwrock** [comment]
Good call on the tests. Just added those and I'll release this as 2.1.0

**Pull request merged**
