### PR TITLE
WinRM certificate-based (password-less) authentication

### PR DESCRIPTION
**Pull request by jfhutchi**
Added support for WinRM certificate-based (password-less) authentication. 
referenced: https://github.com/WinRb/WinRM/issues/199

### CODE REVIEW

**Comment by mwrock** [comment]
This is awesome @jfhutchi and @elpetak !

It would be super cool if you could add a test to https://github.com/WinRb/WinRM/blob/master/spec/transport_spec.rb. You'll probably need to create and add a cert in the appveyor.yml.

Let me know if you need help with that.

**Comment by elpetak** [comment]
@mwrock , the main issue we encountered when trying to create a test for this is with the client cert and it's setup in windows.

We would have to perform these steps in the test setup:
  1. create or upload (beware of the cert expiration date if it's hardcoded) a User certificate
  2. Copy that cert to the Windows VM (we need it on both sides, client and server)
  3. Install the cert in the proper trust stores (Trusted Persons and Trusted Root Certs, if I remember correctly)
  4. Try connecting using the cert as auth method

These guys here: https://cloudbase.it/windows-without-passwords-in-openstack/
have a "create-winrm-client-cert.sh" script that creates a proper user certificate.
But they use cloudbase-init to configure that cert inside the Windows VM. I tried looking at their code but the have a lot of stuff going on in there, it's not a simple script.

If you know how to script that in appveyor then this should be relatively easy. I honestly wouldn't know where to start to script that. In our test box I installed the cert manually.

Is that something you could help us with?

Thanks!

**Comment by mwrock** [comment]
I'll play with this later on and see what I can come up with.

**Comment by mwrock** [comment]
Ive been playing (more like fighting) with certificate based auth. I'm not yet using this PR. First, I'm just trying to get it to work via native winrm. The trouble I'm having it in creating a certificate that winrm will accept. I have used both a .net based approach to creating the cert as well as the bash script @elpetak referred to you. Both immediately fail with:
```
Enter-PSSession : The WinRM client cannot process the request. If you are
using a machine certificate, it must contain a DNS name in the Subject
Alternative Name extension or in the Subject Name field, and no UPN name. If
you are using a user certificate, the Subject Alternative Name extension must
contain a UPN name and must not contain a DNS name. Change the certificate
structure and try the request again.
```
It looks like I have the UPN correct.

I was just curious if @elpetak or @jfhutchi got this working end to end and how the certificate was created. My next attempt will likely be to setup AD certificate services since the one place on the internet I see where someone got this working, they used that to create the cert.

**Comment by elpetak** [comment]
I did the same thing, first try with the normal powershell client. 
I used a client cert generated with the script.
You need to install the cert in the trusted people store and also in the trusted authorities store because it's self signed.
I think you also need to add the cert to the user's personal cert store, but not sure.
Oh, and you certainly need to create a mapping between the cert and the user, there is a command for that but I don't have the details at hand now (afk). Maybe I can add more info tomorrow.

**Comment by elpetak** [comment]
I think this explains it pretty well
http://powershell.org/wp/wp-content/uploads/2013/08/WinRM-Certificate-Authentication.docx

**Comment by mwrock** [comment]
I had actually performed those pre steps and also created the user mapping. I just found that it works from a win7 or 2008R2 client. It is not working on 2012R2 or win 10 clients. However, since the issue is in the "client" it should not be a problem in the ruby winrm which is just a "dumb" soap client and thus not performing any validation. That will be next to try. My OCD is just very bothered right now that native win 10/2012 clients dont work. I'll deal with that on my own though :)

**Comment by jfhutchi** [comment]
That's odd thought we used a Windows Server 2012 standard edition client for our test server..I'll double check

**Comment by mwrock** [comment]
R2 @jfhutchi ? I did not try 2012 (R1). Did you use the bash/openssl script to generate the script? I did find that certs generated via Active Directory Certificate Services worked on 2012R2 clients. So the only thing that broke for me was openssl/.net generated certs on a 2012R2 client, which should be fine for this gem since we don't use the native client.

But I would be curious to know the exact client OS version and method of cert generation you used.

**Comment by jfhutchi** [comment]
Microsoft Windows Server 2012 Standard
6.2.9200 N/A Build 9200

**Comment by elpetak** [comment]
But that's the server. I tested from a Win7 client and I think the other client I used was a 2008, but seems to be down right now so I can't check.

**Comment by elpetak** [comment]
I can confirm that while our test server is 2012r2, the clients I used for testing are Win7 and 2008.

**Comment by mwrock** [comment]
Thanks guys. Good to know our experiences are consistent there.

**Comment by mwrock** [comment]
if interested. I just blogged about this feature: http://www.hurryupandwait.io/blog/certificate-password-less-based-authentication-in-winrm

**Comment by jfhutchi** [comment]
Very cool!

**Comment by elpetak** [comment]
Wait... Who did you talk to? How do you know about the aliens and time travelers?

**Comment by mwrock** [comment]
you told me. future @elpetak

**Comment by mwrock** [comment]
this fixes #199

**Pull request merged**
