### PR TITLE
Relax version pins on dev dependencies

### PR DESCRIPTION
**Pull request by ksubrama**
When bundling winrm with other software (like ChefDK), the highly specific version pins on these dependencies force us to include multiple different versions of rake, rspec and rubocop (because bundler still resolves dev dependencies for consistency, even if we don't install it).  Would you consider relaxing this?

### CODE REVIEW

**Comment by mwrock** [comment]
+1
However it looks like this is causing general unhappiness with rubocop. I'd add the specific versions to the `Gemfile` so the travis runs pass.

**Comment by ksubrama** [comment]
@mwrock Fixed now!

**Comment by mwrock** [comment]
Cool. However it looks like you have made the fixes to get things passing with rubocop 0.33.0 as well, which kinda makes the 0.28.0 `Gemfile` pin unnecessary.

Now I think those white space changes are sensible and it would be better to conform with the latest rubocop. So my 2 cents is drop the `Gemfile` entry and update the `gemspec` to:

```
  s.add_development_dependency 'rspec', '~> 3.3'
  s.add_development_dependency 'rake', '~> 10.4'
  s.add_development_dependency 'rubocop', '~> 0.33'
```

Based on the previously failed travis run, the newer rspec and rakes pose no problem and your other changes should work with the latest rubocop 0.33.0.  To be safe, blow away your `Gemfile.lock` and do a fresh

```
bundle install
bundle exec rake
```

**Comment by mwrock** [comment]
Just occured to me that the above `gemspec` constraints may cause conflicts with chefdk no to mention other scenarios. So I'd just leave them as they are in your commit. With your whitespace changes, I'd just omit your `Gemfile` change.

**Comment by sneal** [comment]
@mwrock Are you happy with these changes as-is? They LGTM.

**Comment by mwrock** [comment]
Yup. The only thing I'd change is removing the `Gemfile` rubocop pin. Since @ksubrama did the right thing and fixed up the violations that made the latest rubocop fail, we don't need to pin to the older version.

If @ksubrama is tied up, this could certainly be merged and the pin removed separately.

**Comment by ksubrama** [comment]
Hey, sorry I am tied up.  I didn't want to break your travis run.  This isn't super critical for me - so if you give me a few days, I'll clean up the rest of the rubocop failures and remove the pin.

**Comment by mwrock** [comment]
Oh rubocop is just fine now. Its just that the `gemfile` entry is now unnecessary. I'm happy to merge this in and remove that.

**Comment by mwrock** [comment]
I'm actually leaving the rubocop pin. After removing it there were still a few violations caught and they looked non trivial to fix in the few minutes I have right now. Thanks @ksubrama !

**Comment by ksubrama** [comment]
Ah that works for me.  Thank you!

**Comment by sneal** [comment]
Thanks guys, released WinRM gem 1.3.4 with this change.

**Pull request merged**
