### PR TITLE
WIP - Psrp implementation

### PR DESCRIPTION
**Pull request by mwrock**
Heh I was just getting back to looking at this and went to rebase latest and noticed @sneal has started working on this (love the message stuff!) and thought we should start a PR where we can collaberate and discuss more easily.

I've started a `protocol` abstraction to encapsulate the XML construction stuff in the service now. Still playing with its structure but hoping that will DRY that out a bit accross the different winrm/psrp implementations.

### CODE REVIEW

**Comment by sneal** [comment]
@mwrock I should have mentioned this to you on Thursday, sorry for not doing that because now we have some duplication between the protocol namespace and the wsmv namespace. The WSMV messages I added will work for either cmd or powershell shells, but using subclasses as you have may be a little cleaner.

While I haven't broken backwards compatibility yet, I'm keeping an eye towards #115. I think now may be the time for winrm v2. 

- The winrm_service interface is getting crufty
- I don't think the new PSRP shell will behave exactly the same as the old run_powershell method
- I'm not sure we even need the old cmd shell.

**Comment by mwrock** [comment]
@sneal Yeah I was thinking the same thing about a v2. I was thinking the initial PSRP release would have a v2 API with back wards compat "shims" that we would remove and refactor out for the v2 release. So sounds like we are on the same page about trying to keep back compat for now.

It looks like the message work you have done so far nicely encapsulates the PSRP body message, I adjusted the Protocol::PSRP class to consume that. With that I don't see duplication. The protocol classes simply intend to encapsulate the SOAP goo. There are some small and important differences in the SOAP structure between winrm and psrp. Relocating the SOAPy stuff to Protocol should clean up the service class quite a bit. However, the protocol classes are VERY much "work in progress" right now and will need some reorganization/cleanup as the interfaces are ironed out.

Very interesting thought about throwing out the `cmd.exe` stuff all together. I hadn't thought of that although its technically feasible since PSRP can should "mostly" handle any cmd.exe call. There are some obscure exceptions.

BTW: I just did a force push of my final rubocop fix that removed your last merge commit which were just an aggregation of my commits from yesterday. Some git thing that I cant coherently explain so I won't try.

**Comment by sneal** [comment]
I've merged our two PSRP branches. The main difference is that everything is in the WSMV module now and the messages don't support any action other than building an XML blobs.

- Still need to DRY some things out, including specs.
- Need to re-implement PSRP, wanted to ensure cmd was working 100% first.
- Need a PSRP executor
- WSMV response messages/handlers? winrm_service is still doing too much. I wish it could delegate everything to the executors, but I'm not sure that's possible without a breaking change.
- Cleanup requires, move to require_relative in winrm_service/winrm module.

**Comment by mwrock** [comment]
So currently we have the `winrm_service` create an executor and the executor calls back to the service for handling SOAP communication (now through the `WSMV` namespace). This could get tricky as we introduce `psrp` and take different strategies to compose the SOAP elements between `winrs` and `psrp` protocols.

It may be easier to have the executor be the one to work with the

**Comment by sneal** [comment]
I'll see what I can do with the executors doing all the message generation and see how shallow I can make the winrm_service. Curious, why is the stand alone keep alive message needed? The way I read the WSMV spec is that should get sent with any request for output (which I added), but with PSRP I see we're sending the stand alone keep alive straight away. I'm assuming that just what you observed via WireShark?

**Comment by mwrock** [comment]
yeah. There were a couple deviations I found in the spec. The most significant one was the need for the `keep_alive` to initialize the runspace. I want to ask someone at MS about this because I'm hoping there is a way we can do this in a single call like the spec mentions. While we do send both the `session_capabilities` and the `init_runspace` fragments in the first call, the second fragment was not registering in the winrm service. I spent alot of time fiddling with this and in the end, sending the keep alive afterwards "magically" worked, which is what I saw `New-PSSession` doing in wireshark.

**Comment by mwrock** [comment]
I ommited the shell and command options for the psrp flavored soap and used explicit args since I dont see those values as configurable but feel free to refactor.

**Comment by sneal** [comment]
I refactored the tests on this branch, and that's about it. I spiked out gutting winrm_service (on the winrm-service-stripdown branch), but it gets pretty ugly. I had to stop because the granularity of the winrm_service is finer than command_executor. To make it work I don't think is worth it.

I spent some time spiking a v2 of winrm (winrm-v2 branch) since it allows us to throw away the API baggage that keeps us from refactoring the code appropriately.

**Comment by mwrock** [comment]
cool. I'll probably start work on getting a psrp friendly output reader next. I believe the "hack" basically bakes a best effort of yanking out the actuual message but it needs to be more precise in finding the actual output in the blob. Maybe your message classes have that functionality but I think they can just `set`.

**Comment by sneal** [comment]
FYI, the cleanup_command WSMV message is broken and the winrm_service is calling the wrong message. Only fixed in the winrm-v2 branch (for now).

**Comment by mwrock** [comment]
rebased this pr on top of current master

**Comment by mwrock** [comment]
The PSRP implementation is now "working" at least to the extent that the initial spike worked.

I added a `PowershellExecutor` class that was mostly a copy paste job of the `CommandExecutor` for now. Didn't notice until I was almost done that there is a `shell` class in v2 that looks eerily similar.

My thoughts on refactoring in v1 is to put most of the wsmv message consumption code of the executor into a `Executor` base class so both executors use it. Then gut the `winrm_service` methods of that code and simply have them call into the `CommandExecutor` - somewhat gross but provides backwards compatibility and v2 would be the "clean path"..

As far as PSRP output is concerned, I'll work on a powershell "flavored" output_decoder that properly extracts the powershell output from the embedded response blob. This will likely include some new logic to the `PSRP::Message` class allowing it to be "hydrated" with a binary blob and exposing the message parts ass attributes.

**Comment by soluwalana** [comment]
@mwrock Awesome work that you've put in here! I've recently found a need to push the PSRP protocol a bit further, I added support for both inbound and outbound fragments in this repository: https://github.com/soluwalana/PSRP-RB
Hopefully it helps.

**Comment by mwrock** [comment]
cool for a more polished version but still not ready for prime time, we are currently working in https://github.com/WinRb/WinRM/tree/winrm-v2

**Comment by soluwalana** [comment]
Are you guys aiming to have PSRP Packet Fragmentation in v2?

**Comment by mwrock** [comment]
eventually @soluwalana but we are currently iterating on a simple implementation without ity and will add it when we need it. Probably when we start working with larger messages to get winrm-fs using it.

**Comment by soluwalana** [comment]
@mwrock dope. Let me know when work is going into that endeavor, I would love to contribute a pull request addressing the PSRP Packet Fragmenting after finally wrapping my head around it for the last 4 days (Binary+XML in Base64 in XML in XML.... would rather no one has to go through this again).

**Comment by mwrock** [comment]
Sure thing. Heh. Yeah there has been alot of head wrapping going on here.

**Comment by mwrock** [comment]
@soluwalana I am going to start digging into the message fragmentation for https://github.com/WinRb/WinRM/pull/191. I was gonna have a look at the repo you linked above but it looks like it is gone now. Do you still have it around somewhere? Since the fragmenting is likely going to introduce a change to our PSRP Message object model, I'm sure we cant simply "drop in" this code but I'm mainly interested in how to determine WHEN to fragment. Where is it specified what the limit of a single fragment is.

I probably need to just look more deeply into the specs. The cursory browsing I have done while waiting in line on my phone has not produced clarity here.

**Comment by soluwalana** [comment]
My company decided to reverse their stance on making it open source recently (last week) and has asked me to remove it from the web. I'll press on the leadership to reconsider though and hopefully get back to you soon.

**Comment by mwrock** [comment]
Hey no worries @soluwalana . I'm gonna do some spec diving when I get a chance and would love to pick your brain afterwards if I can't find the bits I'm looking for.

**Comment by soluwalana** [comment]
Yeah I'm most definitely down to help, the spec was super annoying to get a handle on.

**Comment by mwrock** [comment]
closing in favor of #191

**Comment by mwrock** [comment]
@soluwalana #191 is basically done if you want to have a gander. There ended up being some surprises with the fragmentation/defragmentation mainly that the 32k max blob size limit in the spec is a lie and extending it yields huge perf gains if using this to copy files.

**Pull request closed without merging**
