### PR TITLE
UTF-8 as default codepage

### PR DESCRIPTION
**Pull request by MatthiasWinzeler**
I recently had trouble when echoing strings to stdout/stderr on windows systems (over WinRM) that contained non-ascii chars, especially umlauts (occur in latin1) and other utf8 characters: They were always messed up in the winrm response.

I found that the gem defaultly specifies codepage 437 when opening the shell (https://github.com/WinRb/WinRM/blob/ec9140063bc47f92b52f3a84bde1e4b0800ed911/lib/winrm/winrm_service.rb#L99) so that only characters from this codepage (which contains only the ascii set and some other chars) are displayed correctly. 

When passing the option ```:codepage => 65001``` (which corresponds to utf-8 according to this index: https://msdn.microsoft.com/en-us/library/dd317756(VS.85).aspx) to ```open_shell```, windows successfully receives the utf8 chars. 

But when getting the command output, I get the error ```Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)```. If I add ```force_encoding('utf-8')``` when getting the command output, the error is gone and the utf-8 chars are received correctly on the client (on both windows and linux clients).

In order to support the whole unicode character set in this Gem, this PR changes the default codepage for WinRM shell to utf-8.

Maybe this change is too radical by introducing a new default and will break dependent gems or programs... 
But I couldn't find another solution - adding ```force_encoding('utf-8')``` would break the response when using another codepage as utf-8 for the shell. Nevertheless, I think utf-8 as default seems appropriate nowadays. The spec suite is passing on both windows and linux.

A less intruding alternative (completely backward-compatible): Introduce a ```utf-8 => true``` option that automatically sets the codepage to 650001 and forces the encoding to utf-8 on the output (but leaves the default & other codepages alone) - but I think that would be less elegant.

Spec is included and tested on windows 8.1 & ubuntu linux (ruby 1.9.3) against a windows 2012r2 server.

### CODE REVIEW

**Comment by tmm1** [comment]
Could this be merged?

**Comment by sneal** [comment]
@zenchild @pmorton Is there a reason you can think of where this would cause issues? It seems pretty sensible to default to UTF-8.

**Comment by mwrock** [comment]
This may become a pressing issue. I'm currently trying to setup packer templates for Windows Nano server and its using 65001 and complains when using 437. This will be an issue with the GO package as well.

**Comment by sneal** [comment]
@mwrock Interesting about Nano, but that sounds like a good change. My main worry is backwards compatibility. I'm pretty sure it'll be a safe change, but I was hoping for some additional opinions since I may have missed something.

**Comment by mwrock** [comment]
I just tested against nano, win2012R2, win 8.1 and win 2008R2 endpoints. All were successful. I don't think we need to go any further back than 2008R2. I feel pretty comfortable with this change. @tmm1: would you mind fixing up merge conflicts with master?

**Comment by mwrock** [comment]
@sneal any objection to me fixing the merge conflict here and bumping to 1.3.5.dev?

**Comment by sneal** [comment]
Go for it! I think we've done our due diligence on this one.

**Comment by mwrock** [comment]
cool. done. If you could push a new dev gem to ruby gems whenever you have a chance that would be awesome.

**Comment by sneal** [comment]
@mwrock Done

**Pull request merged**
